### ISSUE TITLE
Sometimes AWTRIX got stuck and no display

### ISSUE THREAD

**Issue by eggface** [awtrix/AWTRIX2.0-Controller#17]
Sometimes AWTRIX got stuck and no display. 

When I checked log, it shows updating and then following with NPE.

`22:34:17      updating Animations
22:34:17      updating Countdown
22:34:19      updating Moon
22:34:19      updating News
22:34:22      updating OpenWeather
java.lang.NullPointerException
	at anywheresoftware.b4j.object.WebSocketModule$Adapter$ThreadHandler.run(WebSocketModule.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

AWTRIX version
01619

Not sure whether it is a known issue.

**Comment by Blueforcer** [comment]
This problem is solved in the latest beta.
Please note this error has nothing to do with the Controller
