### ISSUE TITLE
Frequent OutOfMemoryError

### ISSUE THREAD

**Issue by WestXu** [awtrix/AWTRIX2.0-Controller#51]
I'm using the latest docker from  https://github.com/wHyEt/Awtrix2-Docker with auto-update on.

## log
```
processing Crypto
4:42:04 PM      Updating Crypto
4:43:25 PM      Matrix connection Timeout!
4:43:25 PM      Connecting with WiFi
4:43:48 PM      Matrix has reconnected
4:46:23 PM      Matrix connection Timeout!
4:46:23 PM      Connecting with WiFi
main._appstart (java line: 358)
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.objects.Timer$TickTack$1.run(Timer.java:118)
        at anywheresoftware.b4a.keywords.SimpleMessageLoop.runMessageLoop(SimpleMessageLoop.java:30)
        at anywheresoftware.b4a.StandardBA.startMessageLoop(StandardBA.java:26)
        at anywheresoftware.b4a.keywords.Common.StartMessageLoop(Common.java:153)
        at de.awtrix.main._appstart(main.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at de.awtrix.main.main(main.java:28)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:120)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:36)
        at org.eclipse.moquette.server.netty.NettyAcceptor.initialize(NettyAcceptor.java:102)
        at org.eclipse.moquette.server.Server.startServer(Server.java:96)
        at anywheresoftware.b4j.objects.MqttBroker.Start(MqttBroker.java:73)
        at de.awtrix.matrix._connect(matrix.java:621)
        at de.awtrix.matrix._getinfotimer_tick(matrix.java:2022)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.objects.Timer$TickTack$1.run(Timer.java:118)
        at anywheresoftware.b4a.keywords.SimpleMessageLoop.runMessageLoop(SimpleMessageLoop.java:30)
        at anywheresoftware.b4a.StandardBA.startMessageLoop(StandardBA.java:26)
        at anywheresoftware.b4a.keywords.Common.StartMessageLoop(Common.java:153)
        at de.awtrix.main._appstart(main.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)

main.main (java line: 28)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at de.awtrix.main.main(main.java:28)
Caused by: java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.objects.Timer$TickTack$1.run(Timer.java:118)
        at anywheresoftware.b4a.keywords.SimpleMessageLoop.runMessageLoop(SimpleMessageLoop.java:30)
        at anywheresoftware.b4a.StandardBA.startMessageLoop(StandardBA.java:26)
        at anywheresoftware.b4a.keywords.Common.StartMessageLoop(Common.java:153)
        at de.awtrix.main._appstart(main.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        ... 2 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:120)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:36)
        at org.eclipse.moquette.server.netty.NettyAcceptor.initialize(NettyAcceptor.java:102)
        at org.eclipse.moquette.server.Server.startServer(Server.java:96)
        at anywheresoftware.b4j.objects.MqttBroker.Start(MqttBroker.java:73)
        at de.awtrix.matrix._connect(matrix.java:621)
        at de.awtrix.matrix._getinfotimer_tick(matrix.java:2022)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.objects.Timer$TickTack$1.run(Timer.java:118)
        at anywheresoftware.b4a.keywords.SimpleMessageLoop.runMessageLoop(SimpleMessageLoop.java:30)
        at anywheresoftware.b4a.StandardBA.startMessageLoop(StandardBA.java:26)
        at anywheresoftware.b4a.keywords.Common.StartMessageLoop(Common.java:153)
        at de.awtrix.main._appstart(main.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)

```

## Crashreport-01-16-1650.txt
```
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:120)
        at anywheresoftware.b4a.objects.Timer$TickTack$1.run(Timer.java:118)
        at anywheresoftware.b4a.keywords.SimpleMessageLoop.runMessageLoop(SimpleMessageLoop.java:30)
        at anywheresoftware.b4a.StandardBA.startMessageLoop(StandardBA.java:26)
        at anywheresoftware.b4a.keywords.Common.StartMessageLoop(Common.java:153)
        at de.awtrix.main._appstart(main.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
        at de.awtrix.main.main(main.java:28)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:120)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:36)
        at org.eclipse.moquette.server.netty.NettyAcceptor.initialize(NettyAcceptor.java:102)
        at org.eclipse.moquette.server.Server.startServer(Server.java:96)
        at anywheresoftware.b4j.objects.MqttBroker.Start(MqttBroker.java:73)
        at de.awtrix.matrix._connect(matrix.java:621)
        at de.awtrix.matrix._getinfotimer_tick(matrix.java:2022)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.objects.Timer$TickTack$1.run(Timer.java:118)
        at anywheresoftware.b4a.keywords.SimpleMessageLoop.runMessageLoop(SimpleMessageLoop.java:30)
        at anywheresoftware.b4a.StandardBA.startMessageLoop(StandardBA.java:26)
        at anywheresoftware.b4a.keywords.Common.StartMessageLoop(Common.java:153)
        at de.awtrix.main._appstart(main.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at anywheresoftware.b4a.BA.raiseEvent2(BA.java:91)
        at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
```

**Comment by Blueforcer** [comment]
This is not a controller related problem. Please open a bug report on discord
